Improvement for css styles
MarcinBawolik/Movie-Browser pull request #22
Opened 2023-05-19 21:41 UTC by PatrykSech

Cześć! wstawiam drobne poprawki, związane z designem, stworzyłem rownież podstronę "no result". Czekam, aż wyszukiwarka będzie gotowa, aby móc ją podłączyć. :)

2023-05-20 22:02 UTC, adrianplotka commented on src/common/Banner/styled.js
> +    );
No jak dla mnie za duży jest ten gradient. Powinien on delikatnie wchodzić w zdjęcie, a tu jest tak na oko 40% zakryte, a musi być dużo mniej. Ale zarys całkiem fajny

2023-05-20 22:09 UTC, adrianplotka commented on src/common/Banner/index.js
> +            <MaxRate> / 10</MaxRate>
Do poprawy był odstęp w szczegółach filmu, a nie w banerze. A też nie tak się dodaję odstęp, a w css. A wg to już tutaj jest gap na 8px

2023-05-20 22:22 UTC, adrianplotka commented on src/common/MovieMemberTile/styled.js
> +  height: 231px;
Wydaje mi się, że to rozwiązanie nienaturalnie zwęża zdjęcie

2023-05-20 22:36 UTC, adrianplotka reviewed
Rzeczy, które wskazałem ci do poprawy uważam, że nie są idealnymi rozwiązaniami, ponieważ wprowadzają one inne błedy

2023-05-20 22:36 UTC, adrianplotka commented on src/common/MovieDetailsTile/index.js
No jest teraz lepiej

2023-05-20 22:36 UTC, adrianplotka commented on src/common/Banner/styled.js
No jak dla mnie za duży jest ten gradient. Powinien on delikatnie wchodzić w zdjęcie, a tu jest tak na oko 40% zakryte, a musi być dużo mniej. Ale zarys całkiem fajny

2023-05-20 22:36 UTC, adrianplotka commented on src/common/Banner/index.js
Do poprawy był odstęp w szczegółach filmu, a nie w banerze. A też nie tak się dodaję odstęp, a w css. A wg to już tutaj jest gap na 8px

2023-05-20 22:36 UTC, adrianplotka commented on src/common/MovieMemberTile/styled.js
Wydaje mi się, że to rozwiązanie nienaturalnie zwęża zdjęcie

2023-05-21 08:32 UTC, adrianplotka requested changes

2023-05-21 08:32 UTC, adrianplotka commented on src/common/Banner/index.js
> +            <MaxRate> / 10</MaxRate>
Do poprawy był odstęp w szczegółach filmu, a nie w banerze. A też nie tak się dodaję odstęp, a w css. A wg to już tutaj jest gap na 8px

2023-05-21 08:32 UTC, adrianplotka commented on src/common/Banner/styled.js
> +      #000000 92.87%
No jak dla mnie za duży jest ten gradient. Powinien on delikatnie wchodzić w zdjęcie, a tu jest tak na oko 40% zakryte, a musi być dużo mniej. Ale zarys całkiem fajny

2023-05-21 08:32 UTC, adrianplotka commented on src/common/MovieMemberTile/styled.js
> +  height: 231px;
Wydaje mi się, że to rozwiązanie nienaturalnie zwęża zdjęcie

2023-05-21 21:51 UTC, PatrykSech commented on src/common/Banner/styled.js
> +      #000000 92.87%
Dokładnie taki gradient jest ustawiony w projekcie w figmie, sprawdź sobie jak to wyglada na innych okładkach, być może wybrałeś jedną z tych ciemniejszych i wyglada nienaturalnie

2023-05-22 01:47 UTC, adrianplotka commented on src/common/Banner/styled.js
> +      #000000 92.87%
No obejrzałem kilka filmów i w każdym jest ten sam problem. Gradient chyba rzeczywiście jest okey, ale wtedy problem musi leżeć po innej stronie i pewnie komponent jest za wąski. No, ale trzeba było to poprawić.

2023-05-22 13:42 UTC, PatrykSech commented on src/common/Banner/styled.js
> +      #000000 92.87%
Trochę nie rozumiem w czym jest problem

2023-06-06 15:40 UTC, closed without merging